on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  latest-plus:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - lts/*

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: ${{ matrix.node }}

      - run: echo "y" | rm -Rf my-workspace

      - run: |
          npm i -g @angular/cli
          ng new my-workspace --create-application false
          cd my-workspace
          ng g application my-app --style scss
          ng g library my-lib
          cd projects
          cd my-app
          ng g environments
          ng add @angular-eslint/schematics --skip-confirmation
          npm i prettier -D --save-exact
          npm i eslint-plugin-prettier -D

      - uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
        with:
          title: latest-plus
          body:
          commit-message: latest-plus
          branch: latest-plus
